[build]
  command = "npm run build"
  publish = "dist/open-library-app/browser"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "11.2.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
